module.exports = [
  require("./ping"),
  require("./help"),
  require("./avatar"),
  require("./userinfo"),
  require("./poll"),
  require("./random"),
  require("./choose"),
  require("./clear"),
  require("./anniv"),
  require("./roles"),
  require("./giveaway"),
  require("./money"),
  require("./casino"),
  require("./afk"),
  require("./quote"),
  require("./ticket"),
  require("./level"),
  require("./warn"),
  require("./suggest"),
  require("./botstatus"),
  require("./quests"),
  require("./duel"),
  require("./girlsss"),
  require("./gazette"),
  require("./dashboard"),
  require("./devlog"),
].filter((cmd) => require("../lib/serverProfile").isCommandEnabled(cmd.data.name));
