module.exports = {
  currency: "coins",
  startBalance: 100,
  daily: { min: 80, max: 150, cooldownMs: 24 * 60 * 60 * 1000 },
  dailyStreak: { bonusPerDay: 12, maxBonus: 120 },
  work: { min: 15, max: 45, cooldownMs: 45 * 60 * 1000 },
  bet: { min: 10, maxAbsolute: 2000, maxBalanceRatio: 0.75 },
  bankLoan: {
    interestRate: 0.2,
    minAmount: 100,
    maxAmount: 1500,
    cooldownMs: 48 * 60 * 60 * 1000,
    dueMs: 7 * 24 * 60 * 60 * 1000,
    blockCasinoWhileDebt: false,
    blockCasinoWhenOverdue: true,
  },
  pay: {
    dailyLimitPerUser: 5000,
    dailyLimitToSameUser: 2000,
    alertThreshold: 1000,
  },
  coinflip: { multiplier: 1.9 },
  dice: { multiplier: 5 },
  roulette: {
    red: { numbers: [1, 3, 5, 7, 9], multiplier: 2 },
    black: { numbers: [2, 4, 6, 8], multiplier: 2 },
    green: { numbers: [0], multiplier: 9 },
    straight: { multiplier: 9 },
  },
  blackjack: { blackjackMultiplier: 2.5, winMultiplier: 2, pushReturn: true },
  jackpot: { taxRate: 0.03, winChance: 1 / 180 },
  slots: {
    symbols: [
      { id: "cherry", emoji: "🍒", weight: 38 },
      { id: "lemon", emoji: "🍋", weight: 28 },
      { id: "star", emoji: "⭐", weight: 18 },
      { id: "diamond", emoji: "💎", weight: 11 },
      { id: "seven", emoji: "7️⃣", weight: 5 },
    ],
    payouts: {
      three: { seven: 10, diamond: 5, star: 3, lemon: 2, cherry: 1.5 },
      pair: 1.15,
    },
  },
};
